urbanclip_templates = [
        '{}',
        'A street photo of {} with cars.',
        'A street photo of {} with parking lot.',
        'A street photo of {} on the road.',
        'A street photo of {} with many trees.',
        'A street photo of {} in city.',
    ]

urbanclip_templates_sc_shenzhen = [
        '{} in Shenzhen',
        'A street photo of {} with cars in Shenzhen.',
        'A street photo of {} with parking lot in Shenzhen.',
        'A street photo of {} on the road in Shenzhen.',
        'A street photo of {} with many trees in Shenzhen.',
        'A street photo of {} in Shenzhen.',
    ]

urbanclip_templates_sc_london = [
        '{}',
        'A street photo of {} with cars in London.',
        'A street photo of {} with parking lot in London.',
        'A street photo of {} on the road in London.',
        'A street photo of {} with many trees in London.',
        'A street photo of {} in London.',
    ]

urbanclip_templates_sc_singapore = [
        '{}',
        'A street photo of {} with cars in Singapore.',
        'A street photo of {} with parking lot in Singapore.',
        'A street photo of {} on the road in Singapore.',
        'A street photo of {} with many trees in Singapore.',
        'A street photo of {} in Singapore.',
    ]

photo_templates = [
    'A photo of a {}.',
    ]

openai80_templates = [
        'a bad photo of a {}.',
        'a photo of many {}.',
        'a sculpture of a {}.',
        'a photo of the hard to see {}.',
        'a low resolution photo of the {}.',
        'a rendering of a {}.',
        'graffiti of a {}.',
        'a bad photo of the {}.',
        'a cropped photo of the {}.',
        'a tattoo of a {}.',
        'the embroidered {}.',
        'a photo of a hard to see {}.',
        'a bright photo of a {}.',
        'a photo of a clean {}.',
        'a photo of a dirty {}.',
        'a dark photo of the {}.',
        'a drawing of a {}.',
        'a photo of my {}.',
        'the plastic {}.',
        'a photo of the cool {}.',
        'a close-up photo of a {}.',
        'a black and white photo of the {}.',
        'a painting of the {}.',
        'a painting of a {}.',
        'a pixelated photo of the {}.',
        'a sculpture of the {}.',
        'a bright photo of the {}.',
        'a cropped photo of a {}.',
        'a plastic {}.',
        'a photo of the dirty {}.',
        'a jpeg corrupted photo of a {}.',
        'a blurry photo of the {}.',
        'a photo of the {}.',
        'a good photo of the {}.',
        'a rendering of the {}.',
        'a {} in a video game.',
        'a photo of one {}.',
        'a doodle of a {}.',
        'a close-up photo of the {}.',
        'a photo of a {}.',
        'the origami {}.',
        'the {} in a video game.',
        'a sketch of a {}.',
        'a doodle of the {}.',
        'a origami {}.',
        'a low resolution photo of a {}.',
        'the toy {}.',
        'a rendition of the {}.',
        'a photo of the clean {}.',
        'a photo of a large {}.',
        'a rendition of a {}.',
        'a photo of a nice {}.',
        'a photo of a weird {}.',
        'a blurry photo of a {}.',
        'a cartoon {}.',
        'art of a {}.',
        'a sketch of the {}.',
        'a embroidered {}.',
        'a pixelated photo of a {}.',
        'itap of the {}.',
        'a jpeg corrupted photo of the {}.',
        'a good photo of a {}.',
        'a plushie {}.',
        'a photo of the nice {}.',
        'a photo of the small {}.',
        'a photo of the weird {}.',
        'the cartoon {}.',
        'art of the {}.',
        'a drawing of the {}.',
        'a photo of the large {}.',
        'a black and white photo of a {}.',
        'the plushie {}.',
        'a dark photo of a {}.',
        'itap of a {}.',
        'graffiti of the {}.',
        'a toy {}.',
        'itap of my {}.',
        'a photo of a cool {}.',
        'a photo of a small {}.',
        'a tattoo of the {}.',
    ]

wu_templates_shenzhen = [
            '{} place in Shenzhen',
            '{} land use in Shenzhen',
            '{} use in Shenzhen',
            '{} in Shenzhen',
            'for {} in New York',
            '{} area in Shenzhen',
            '{} purpose in Shenzhen',
        ]

wu_templates_london = [
            '{} place in London',
            '{} land use in London',
            '{} use in London',
            '{} in London',
            'for {} in London',
            '{} area in London',
            '{} purpose in London',
        ]

wu_templates_singapore = [
            '{} place in Singapore',
            '{} land use in Singapore',
            '{} use in Singapore',
            '{} in Singapore',
            'for {} in Singapore',
            '{} area in Singapore',
            '{} purpose in Singapore',
        ]

wu_templates_no_sc = [
            '{} place',
            '{} land use',
            '{} use',
            '{}',
            'for {}',
            '{} area',
            '{} purpose',
        ]
